pipeline:
  name: samdeploy
  identifier: samdeploy
  projectIdentifier: serverless
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: aws-auth
        identifier: awsauth
        description: ""
        type: Custom
        spec:
          execution:
            steps:
              - step:
                  type: ShellScript
                  name: ShellScript_1
                  identifier: ShellScript_1
                  spec:
                    shell: Bash
                    executionTarget: {}
                    source:
                      type: Inline
                      spec:
                        script: cat /etc/os-release
                    environmentVariables: []
                    outputVariables: []
                  timeout: 10m
        tags: {}
