pipeline:
  name: samdeploy
  identifier: samdeploy
  projectIdentifier: serverless
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: sam-deploy
        identifier: samdeploy
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          caching:
            enabled: true
            override: true
          buildIntelligence:
            enabled: true
          infrastructure:
            type: KubernetesDirect
            spec:
              connectorRef: infra1
              namespace: dev
              automountServiceAccountToken: true
              nodeSelector: {}
              os: Linux
          execution:
            steps:
              - step:
                  type: Background
                  name: Background_1
                  identifier: Background_1
                  spec:
                    connectorRef: docker
                    image: " docker:29.2.1-dind-alpine3.23"
                    shell: Sh
                    privileged: true
                    entrypoint:
                      - docker-entrypoint.sh
                      - "--mtu=6000"
              - step:
                  type: Run
                  name: Run_1
                  identifier: Run_1
                  spec:
                    connectorRef: docker
                    image: redhat/ubi9-minimal:latest
                    shell: Sh
                    command: |-
                      cat /etc/os-release
                      curl -O https://www.rpmfind.net/linux/almalinux/8.10/BaseOS/x86_64/os/Packages/unzip-6.0-48.el8_10.x86_64.rpm
                      rpm -i unzip-6.0-48.el8_10.x86_64.rpm
                      curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"

                      unzip awscliv2.zip
                      ./aws/install

                      aws --version

                      export AWS_ACCESS_KEY_ID="<+secrets.getValue("aws-accesskey")>"
                      export AWS_SECRET_ACCESS_KEY="<+secrets.getValue("aws-secret")>"
                      export AWS_DEFAULT_REGION="us-east-1"

                      aws sts get-caller-identity

                      curl -L https://github.com/aws/aws-sam-cli/releases/latest/download/aws-sam-cli-linux-x86_64.zip -o aws-sam-cli-linux-x86_64.zip

                      mkdir sam-installation
                      unzip aws-sam-cli-linux-x86_64.zip -d sam-installation
                      ./sam-installation/install
                      sam --version

                      sam build
  properties:
    ci:
      codebase:
        connectorRef: github
        repoName: SAM-app
        build: <+input>
